url: https://hausemodelica.github.io/modelica-standards
baseurl: /modelica-standards

collections:
  events:
    output: true
  releases:
    output: true
  footer_pages:
    output: true



defaults:
  - scope:
      path: ""
    values:
      layout: "home"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

