url: https://c-papabechtelou.github.io/second-template

collections:
  events:
    output: true
  releases:
    output: true



defaults:
  - scope:
      path: ""
    values:
      layout: "home"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

